version: "3.7"

services:
  alpha:
      build:
        context: https://github.com/AftahBagas/Alpha.git#Alpha
      depends_on:
        - mongo
      restart: on-failure
      environment:
          DATABASE_URL: mongodb://root:example@mongo
      env_file:
        - config.env

  mongo:
      image: mongo
      volumes:
        - mongo_alpha:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo_alpha:
